# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pydata.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpydata.proto\x12\x02rl\"\xf0\x02\n\x06RLData\x12)\n\x0frestPlotsOfType\x18\x01 \x03(\x0b\x32\x10.rl.RLData.plots\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x11\n\tliquidity\x18\x03 \x01(\x02\x12\x12\n\nmanagement\x18\x04 \x01(\x02\x12\x30\n\x0brestInvests\x18\x05 \x03(\x0b\x32\x1b.rl.RLData.RestInvestsEntry\x12\x13\n\x0brecentRents\x18\x06 \x03(\x01\x12\x12\n\nnfarms10km\x18\x07 \x01(\x05\x12\x16\n\x0enfreeplots10km\x18\x08 \x03(\x05\x12\x12\n\navNewRents\x18\t \x03(\x01\x1a\x46\n\x10RestInvestsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.rl.RLData.invlife:\x02\x38\x01\x1a\x12\n\x05plots\x12\t\n\x01n\x18\x01 \x03(\x05\x1a$\n\x07invlife\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12\x0c\n\x04life\x18\x02 \x01(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pydata_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RLDATA_RESTINVESTSENTRY._options = None
  _RLDATA_RESTINVESTSENTRY._serialized_options = b'8\001'
  _RLDATA._serialized_start=21
  _RLDATA._serialized_end=389
  _RLDATA_RESTINVESTSENTRY._serialized_start=261
  _RLDATA_RESTINVESTSENTRY._serialized_end=331
  _RLDATA_PLOTS._serialized_start=333
  _RLDATA_PLOTS._serialized_end=351
  _RLDATA_INVLIFE._serialized_start=353
  _RLDATA_INVLIFE._serialized_end=389
# @@protoc_insertion_point(module_scope)
